### ISSUE TITLE
ImportError: No module named torchnet.meter

### ISSUE THREAD

**Issue by Oliverwang** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#11]
Traceback (most recent call last):
  File "head_detection_demo.py", line 7, in <module>
    from trainer import Head_Detector_Trainer
  File "/home/mrsy/project/head_detect/FCHD-Fully-Convolutional-Head-Detector/trainer.py", line 9, in <module>
    from torchnet.meter import ConfusionMeter, AverageValueMeter
ImportError: No module named torchnet.meter

**Comment by millanp95** [comment]
I'm having the same problem. Can you please tell me how did you fix it ?

**Comment by sunjunlishi** [comment]
my error too
