### ISSUE TITLE
run demo error

### ISSUE THREAD

**Issue by Oliverwang** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#12]
oints/head_detector_final 
test_image/test3.jpg
checkpoints/head_detector_final
(600.0, 789.7172236503856)
WARNING:root:Setting up a new session...
Traceback (most recent call last):
  File "head_detection_demo.py", line 73, in <module>
    detect(args.img_path, args.model_path)
  File "head_detection_demo.py", line 51, in detect
    pred_bboxes_, _ = head_detector.predict(img, scale, mode='evaluate', thresh=THRESH)
  File "/home/mrsy/project/head_detect/FCHD-Fully-Convolutional-Head-Detector/src/head_detector.py", line 72, in predict
    _, _, rois, rois_scores, _ = self.forward(x, scale=scale)
  File "/home/mrsy/project/head_detect/FCHD-Fully-Convolutional-Head-Detector/src/head_detector.py", line 26, in forward
    rpn_locs, rpn_scores, rois, rois_scores, anchor = self.rpn(h, img_size, scale)
  File "/usr/local/lib/python2.7/dist-packages/torch/nn/modules/module.py", line 477, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/mrsy/project/head_detect/FCHD-Fully-Convolutional-Head-Detector/src/region_proposal_network.py", line 79, in forward
    scale=scale
  File "/home/mrsy/project/head_detect/FCHD-Fully-Convolutional-Head-Detector/src/creator_tool.py", line 147, in __call__
    thresh=self.nms_thresh)
  File "/home/mrsy/project/head_detect/FCHD-Fully-Convolutional-Head-Detector/src/nms/non_maximum_suppression.py", line 72, in non_maximum_suppression
    return _non_maximum_suppression_gpu(bbox, thresh, score, limit)
  File "/home/mrsy/project/head_detect/FCHD-Fully-Convolutional-Head-Detector/src/nms/non_maximum_suppression.py", line 84, in _non_maximum_suppression_gpu
    order = cp.arange(n_bbox, dtype=np.int32)
  File "/usr/local/lib/python2.7/dist-packages/cupy/creation/ranges.py", line 57, in arange
    _arange_ufunc(typ(start), typ(step), ret, dtype=dtype)
  File "cupy/core/_kernel.pyx", line 821, in cupy.core._kernel.ufunc.__call__
  File "cupy/util.pyx", line 48, in cupy.util.memoize.decorator.ret
  File "cupy/core/_kernel.pyx", line 612, in cupy.core._kernel._get_ufunc_kernel
  File "cupy/core/_kernel.pyx", line 46, in cupy.core._kernel._get_simple_elementwise_kernel
  File "cupy/core/carray.pxi", line 148, in cupy.core.core.compile_with_cache
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 164, in compile_with_cache
    ptx = compile_using_nvrtc(source, options, arch)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 82, in compile_using_nvrtc
    ptx = prog.compile(options)
  File "/usr/local/lib/python2.7/dist-packages/cupy/cuda/compiler.py", line 245, in compile
    raise CompileException(log, self.src, self.name, options)
cupy.cuda.compiler.CompileException: /usr/local/cuda-8.0/include/cuda_fp16.h(2958): error: identifier "__float2half_rn" is undefined

/usr/local/cuda-8.0/include/cuda_fp16.h(3000): error: identifier "__float2half_rn" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(55): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(45): error: no suitable constructor exists to convert from "float" to "__half"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(47): error: no suitable constructor exists to convert from "float" to "__half"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(48): error: no suitable constructor exists to convert from "double" to "__half"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(49): error: no suitable constructor exists to convert from "int" to "__half"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(50): error: no suitable constructor exists to convert from "unsigned int" to "__half"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(51): error: no suitable constructor exists to convert from "long long" to "__half"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(52): error: no suitable constructor exists to convert from "unsigned long long" to "__half"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(57): error: no suitable conversion function from "const half" to "float" exists

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(62): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(66): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(66): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(71): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(75): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(79): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(107): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(107): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(108): error: expected a ";"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(109): error: expected a ";"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(110): error: identifier "ret_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(110): error: identifier "y_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(115): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(115): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(116): error: expected a ";"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(117): error: expected a ";"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(119): error: identifier "ret_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(121): error: identifier "ret_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(123): error: identifier "ret_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(123): error: identifier "y_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(125): error: identifier "y_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(126): error: identifier "ret_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(128): error: identifier "ret_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(130): error: identifier "y_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(131): error: identifier "ret_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(133): error: identifier "ret_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(135): error: identifier "ret_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(140): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(140): error: identifier "__half_raw" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(141): error: expected a ";"

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(142): error: identifier "y_raw_" is undefined

/usr/local/lib/python2.7/dist-packages/cupy/core/include/cupy/carray.cuh(281): warning: statement is unreachable
          detected during instantiation of "void CIndexer<_ndim>::set(ptrdiff_t) [with _ndim=1]" 
/tmp/tmpom81Le/kern.cu(12): here

42 errors detected in the compilation of "/tmp/tmpom81Le/kern.cu".

Here is the detail of my environment:

Ubuntu 16.04
Python 2.7
PyTorch 0.41 with GPU
cupy-cuda80
CUDA Version 8.0.61

**Comment by sharonjunjun** [comment]
i have meet the same bug, have you find the reason?

**Comment by Oliverwang** [comment]
I suspect the problem with the cuda version, but no verification

**Comment by Oliverwang** [comment]
我 qQ   404647184  可以一起探讨一下这个问题

**Comment by xiaoshuzhijia** [comment]
I meet the same err,have you find how to solve it?

**Comment by negi111111** [comment]
I'm also bothered by the same error.

**Comment by kmaehashi** [comment]
Hi, could you try setting `CUDA_PATH` and `LD_LIBRARY_PATH`?

> CuPy always raises cupy.cuda.compiler.CompileException

https://docs-cupy.chainer.org/en/latest/install.html#cupy-always-raises-cupy-cuda-compiler-compileexception

**Comment by dongxijia** [comment]
> Hi, could you try setting `CUDA_PATH` and `LD_LIBRARY_PATH`?
> 
> > CuPy always raises cupy.cuda.compiler.CompileException
> 
> https://docs-cupy.chainer.org/en/latest/install.html#cupy-always-raises-cupy-cuda-compiler-compileexception

I tried the soulution, but the problem still there. Is there any other way to solve this problem, any idea could help. Thanks a lot!

**Comment by bailvwangzi** [comment]
same problem. @dongxijia have you solved?
