### ISSUE TITLE
when doing demo cuDnn error occurs

### ISSUE THREAD

**Issue by Chenyangzh** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#16]
Traceback (most recent call last):
  File "D:/Program/Pyproject/resources/Code/Head_Detection/FCHD-Fully-Convolutional-Head-Detector-master/head_detection_demo.py", line 69, in <module>
    detect(args.img_path, args.model_path)
  File "D:/Program/Pyproject/resources/Code/Head_Detection/FCHD-Fully-Convolutional-Head-Detector-master/head_detection_demo.py", line 49, in detect
    pred_bboxes_, _ = head_detector.predict(img, scale, mode='evaluate', thresh=THRESH)
  File "D:\Program\Pyproject\resources\Code\Head_Detection\FCHD-Fully-Convolutional-Head-Detector-master\src\head_detector.py", line 72, in predict
    _, _, rois, rois_scores, _ = self.forward(x, scale=scale)
  File "D:\Program\Pyproject\resources\Code\Head_Detection\FCHD-Fully-Convolutional-Head-Detector-master\src\head_detector.py", line 25, in forward
    h = self.extractor(x)
  File "D:\Program\Python3.6\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program\Python3.6\lib\site-packages\torch\nn\modules\container.py", line 92, in forward
    input = module(input).cuda()
  File "D:\Program\Python3.6\lib\site-packages\torch\nn\modules\module.py", line 489, in __call__
    result = self.forward(*input, **kwargs)
  File "D:\Program\Python3.6\lib\site-packages\torch\nn\modules\conv.py", line 320, in forward
    self.padding, self.dilation, self.groups).cuda()
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED

Process finished with exit code 1

I don't know what happen here! every thing are correct! I am using python3.6 CUDA9 vs2017community

**Comment by aditya-vora** [comment]
@Chenyangzh Have you installed cuDNN ?
