### ISSUE TITLE
ConnectionRefusedError

### ISSUE THREAD

**Issue by dongxijia** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#27]
Dear author, I met a problem when I run the head_detection_demo. Here is the error:
the python code for non_maximum_suppression is about 2x slow
    It is strongly recommended to build cython code: 
    `cd model/utils/nms/; python3 build.py build_ext --inplace
  `cd model/utils/nms/; python3 build.py build_ext --inplace''')
/home/sobey/.local/lib/python3.6/site-packages/skimage/transform/_warps.py:110: UserWarning: Anti-aliasing will be enabled by default in skimage 0.15 to avoid aliasing artifacts when down-sampling images.
  warn("Anti-aliasing will be enabled by default in skimage 0.15 to "
WARNING:root:Setting up a new session...
Exception in user code:
------------------------------------------------------------
Traceback (most recent call last):
  File "/home/sobey/.local/lib/python3.6/site-packages/urllib3/connection.py", line 159, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/home/sobey/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 80, in create_connection
    raise err
  File "/home/sobey/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 70, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

Any idea could help, thanks a lot!

**Comment by KelvinHuang666** [comment]
端口占用，重新指定端口

**Comment by mengyingfei** [comment]
Please start the visdom service with the "python -m visdom.server" command before run head_detection_demo.py
