### ISSUE TITLE
hi, python head_detection_demo.py have error

### ISSUE THREAD

**Issue by zhanghongruiupup** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#58]
python head_detection_demo.py --img_path /home/fwq/pic/1.png  --model_path /home/fwq/zhanghongruils/head/fchd/model/head_detector_final 

info:
 the python code for non_maximum_suppression is about 2x slow
    It is strongly recommended to build cython code: 
    `cd model/utils/nms/; python3 build.py build_ext --inplace
  `cd model/utils/nms/; python3 build.py build_ext --inplace''')
Setting up a new session...
Traceback (most recent call last):
  File "head_detection_demo.py", line 69, in <module>
    detect(args.img_path, args.model_path)
  File "head_detection_demo.py", line 49, in detect
    pred_bboxes_, _ = head_detector.predict(img, scale, mode='evaluate', thresh=THRESH)
  File "/home/fwq/zhanghongruils/head/fchd/src/head_detector.py", line 72, in predict
    _, _, rois, rois_scores, _ = self.forward(x, scale=scale)
  File "/home/fwq/zhanghongruils/head/fchd/src/head_detector.py", line 26, in forward
    rpn_locs, rpn_scores, rois, rois_scores, anchor = self.rpn(h, img_size, scale)
  File "/home/fwq/anaconda3/lib/python3.6/site-packages/torch/nn/modules/module.py", line 547, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/fwq/zhanghongruils/head/fchd/src/region_proposal_network.py", line 79, in forward
    scale=scale
  File "/home/fwq/zhanghongruils/head/fchd/src/creator_tool.py", line 150, in __call__
    roi = roi[keep,:]
ValueError: object __array__ method not producing an array

hope your reply

**Comment by kimsent** [comment]
can you please upload the weights? i cannot download it.
