### ISSUE TITLE
CUDA driver version is insufficient for CUDA runtime version

### ISSUE THREAD

**Issue by chuanheliu** [aditya-vora/FCHD-Fully-Convolutional-Head-Detector#7]
Thanks for your sharing and sorry for submit for 3 times (including 2 wrong issues)

I have installed all the dependency and changed the config.py file to the right path
However, errors ocour when I run the demo.
```
 Traceback (most recent call last):
  File "/home/lch/.local/lib/python2.7/site-packages/visdom/__init__.py", line 446, in _send
    data=json.dumps(msg),
  File "/home/lch/.local/lib/python2.7/site-packages/requests/api.py", line 112, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/lch/.local/lib/python2.7/site-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/lch/.local/lib/python2.7/site-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lch/.local/lib/python2.7/site-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/home/lch/.local/lib/python2.7/site-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
ConnectionError: HTTPConnectionPool(host='localhost', port=8097): Max retries exceeded with url: /env/head_detector (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f7a57fd6dd0>: Failed to establish a new connection: [Errno 111] Connection refused',))
THCudaCheck FAIL file=/pytorch/aten/src/THC/THCGeneral.cpp line=74 error=35 : CUDA driver version is insufficient for CUDA runtime version
Traceback (most recent call last):
  File "head_detection_demo.py", line 69, in <module>
    detect(args.img_path, args.model_path)
  File "head_detection_demo.py", line 43, in detect
    trainer = Head_Detector_Trainer(head_detector).cuda()
  File "/home/lch/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 258, in cuda
    return self._apply(lambda t: t.cuda(device))
  File "/home/lch/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/lch/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/lch/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 185, in _apply
    module._apply(fn)
  File "/home/lch/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 191, in _apply
    param.data = fn(param.data)
  File "/home/lch/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 258, in <lambda>
    return self._apply(lambda t: t.cuda(device))
RuntimeError: cuda runtime error (35) : CUDA driver version is insufficient for CUDA runtime version at /pytorch/aten/src/THC/THCGeneral.cpp:74
```

Here is the detail of my environment:

Ubuntu 16.04
Python 2.7
PyTorch 0.4 with GPU
cupy-cuda80
CUDA Version 8.0.44
CUDNN Version 5.1.5
NVIDIA-SMI 375.82

Is there anything wrong with my environment?

Thanks

**Comment by aditya-vora** [comment]
@chuanheliu I think you are having issues with CUDA. You can search it on the internet in order to solve this. This is a very common issue.
